server {
    listen 80;
    client_max_body_size 20M;

    location /assets/ {
        root /usr/share/nginx/html;
        add_header Cache-Control "public, max-age=2592000" always;
        add_header CDN-Cache-Control "public, max-age=2592000" always;
        add_header Cloudflare-CDN-Cache-Control "public, max-age=2592000" always;
        try_files $uri =404;
    }

    location ~* \.(?:js|mjs|css|map|json|png|jpg|jpeg|gif|svg|ico|webp|avif|woff|woff2|ttf|eot|glb|gltf|hdr)$ {
        root /usr/share/nginx/html;
        add_header Cache-Control "public, max-age=2592000" always;
        add_header CDN-Cache-Control "public, max-age=2592000" always;
        add_header Cloudflare-CDN-Cache-Control "public, max-age=2592000" always;
        try_files $uri =404;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        add_header Cache-Control "public, max-age=2592000" always;
        add_header CDN-Cache-Control "public, max-age=2592000" always;
        add_header Cloudflare-CDN-Cache-Control "public, max-age=2592000" always;
        try_files $uri $uri/ /index.html;
    }
}
